---
network:
  plugin: flannel
  options:
    flannel_image: rancher/coreos-flannel:v0.9.1
    flannel_cni_image: rancher/coreos-flannel-cni:v0.2.0

nodes:
  - address: 172.16.252.220
    user: user01
    role: [controlplane, etcd,worker]

services:
  etcd:
    image: rancher/etcd:v3.0.17
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {"fail-swap-on":"false"}
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2

system_images:
  alpine: alpine
  nginx_proxy: rancher/rke-nginx-proxy:v0.1.1
  cert_downloader: rancher/rke-cert-deployer:v0.1.1
  service_sidekick_image: rancher/rke-service-sidekick:v0.1.0
  kubedns_image: rancher/k8s-dns-kube-dns-amd64:1.14.5
  dnsmasq_image: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.5
  kubedns_sidecar_image: rancher/k8s-dns-sidecar-amd64:1.14.5
  kubedns_autoscaler_image: rancher/cluster-proportional-autoscaler-amd64:1.0.0
